#!/usr/bin/env pwsh
# Installs the Chromium browser (plus OS-level dependencies, on Linux) that
# BrowserTraceTests needs, using the playwright.ps1 generated by building
# Sherland.Aspire.DemoTests. Builds the test project only if that output is
# missing. Safe to run repeatedly.
[CmdletBinding()]
param(
    [string]$Configuration = 'Debug'
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$testProject = Join-Path $repoRoot 'samples' 'Sherland.Aspire.DemoTests' 'Sherland.Aspire.DemoTests.csproj'
$outputDir = Join-Path $repoRoot 'samples' 'Sherland.Aspire.DemoTests' 'bin' $Configuration

function Find-PlaywrightScript {
    if (Test-Path $outputDir) {
        return Get-ChildItem -Path $outputDir -Filter 'playwright.ps1' -Recurse | Select-Object -First 1
    }
    return $null
}

$playwrightScript = Find-PlaywrightScript

if (-not $playwrightScript) {
    Write-Host "playwright.ps1 not found under $outputDir; building $testProject first."
    dotnet build $testProject -c $Configuration
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet build failed with exit code $LASTEXITCODE."
    }

    $playwrightScript = Find-PlaywrightScript
    if (-not $playwrightScript) {
        throw "playwright.ps1 was not found under $outputDir even after building."
    }
}

pwsh $playwrightScript.FullName install --with-deps chromium
